spring:
  application:
    name: ecommerce
  data-source:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: tyler
    password: marla
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  access:
    expiration: 900000
  refresh:
    expiration: 604800000
  secret: cHJvamVjdCBvbmUgZWNvbW1lcmNlIG1hbmFnZW1lbnQgc3lzdGVt